export const TERM_DASHBOARD = 'Dashboard'
export const TERM_DASHBOARDS = 'Dashboards'

export const TERM_DATA = 'Data'
export const TERM_ENTITY = 'Entity'
export const TERM_ENTITIES = 'Entities'
export const TERM_ENTITY_ITEM = 'Item'
export const TERM_ENTITY_ITEMS = 'Items'
export const TERM_COLLECTION = 'Collection'
export const TERM_COLLECTIONS = 'Collections'

export const TERM_VALUE = 'Value'
export const TERM_VALUES = 'Values'
export const TERM_VARIABLE = 'Variable'
export const TERM_VARIABLES = 'Variables'
export const TERM_CONSTANT = 'Constants'
export const TERM_CONSTANTS = 'Constants'

export const TERM_AUTOMATE = 'Automate'
export const TERM_ACTION = 'Action'
export const TERM_ACTIONS = 'Actions'
export const TERM_WORKFLOW = 'Workflow'
export const TERM_WORKFLOWS = 'Workflows'
export const TERM_TRIGGER = 'Trigger'
export const TERM_TRIGGERS = 'Triggers'
export const TERM_ENDPOINT = 'Endpoint'
export const TERM_ENDPOINTS = 'Endpoints'

export const TERM_APP = 'App'
export const TERM_APPS = 'Apps'
